# Generated by Django 2.2.5 on 2019-11-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question_text', models.CharField(max_length=200)),
                ('answer_choice_one', models.CharField(max_length=50)),
                ('answer_choice_two', models.CharField(max_length=50)),
                ('answer_choice_three', models.CharField(max_length=50)),
                ('answer_choice_four', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.IntegerField(default=1000)),
                ('student_email', models.CharField(max_length=40)),
                ('student_name', models.CharField(max_length=20)),
                ('student_marks', models.IntegerField(default=0)),
            ],
        ),
    ]
